// app.js — Main Application Controller (MeetScribe)
// Runs in the standalone tab (app.html) context.
// Orchestrates: audio capture → speech recognition → Gemini → download.

import { AudioCapture } from "./audio.js";
import { SpeechTranscriber } from "./speech.js";
import { generateMinutes, transcribeTabAudio } from "./gemini.js";
import { downloadFile, storageGet, storageSet, formatTimestamp, formatDuration, cleanTranscript } from "./utils.js";

// ── Simple Markdown → HTML renderer ──────────────────────────────────────────
function renderMarkdown(md) {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^---$/gm, "<hr/>")
    .replace(/^\> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/^\| (.+) \|$/gm, (_, row) => {
      const cells = row.split(" | ");
      const isHeader = false;
      return `<tr>${cells.map(c => `<td>${c.trim()}</td>`).join("")}</tr>`;
    })
    .replace(/(<tr>.*<\/tr>\n?)+/gs, m => `<table>${m}</table>`)
    .replace(/^- \[ \] (.+)$/gm, "<li>☐ $1</li>")
    .replace(/^- \[x\] (.+)$/gm, "<li>☑ $1</li>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/^(\d+)\. (.+)$/gm, "<li>$1. $2</li>")
    .replace(/(<li>.*<\/li>\n?)+/gs, m => `<ul>${m}</ul>`)
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hupbtc]|<li|<hr|<bloc)(.+)$/gm, "<p>$1</p>")
    .replace(/<p><\/p>/g, "")
    .replace(/\*Generated by MeetScribe AI.+\*/g, m => `<em style="color:var(--text-muted);font-size:11px;">${m}</em>`);
}

// ─────────────────────────────────────────────────────────────────────────────
//  DOM REFS
// ─────────────────────────────────────────────────────────────────────────────
const btnStart       = document.getElementById("btn-start");
const btnStop        = document.getElementById("btn-stop");
const btnGenerate    = document.getElementById("btn-generate");
const btnDownload    = document.getElementById("btn-download");
const btnTranscript  = document.getElementById("btn-transcript");
const statusBadge    = document.getElementById("status-badge");
const statusText     = document.getElementById("status-text");
const sessionClock   = document.getElementById("session-clock");
const waveIndicator  = document.getElementById("wave-indicator");
const alertBanner    = document.getElementById("alert-banner");
const alertTextEl    = document.getElementById("alert-text");
const transcriptEl   = document.getElementById("transcript-display");
const transcriptEmpty= document.getElementById("transcript-empty");
const minutesEl      = document.getElementById("minutes-display");
const minutesEmpty   = document.getElementById("minutes-empty");
const loadingOverlay = document.getElementById("loading-overlay");
const loadingText    = document.getElementById("loading-text");
const loadingSub     = document.getElementById("loading-sub");
const apiKeyInput    = document.getElementById("api-key-input");
const toggleKeyBtn   = document.getElementById("toggle-key");
const langSelect     = document.getElementById("lang-select");
const micStatus      = document.getElementById("mic-status");
const micDetail      = document.getElementById("mic-detail");
const tabStatus        = document.getElementById("tab-status");
const tabDetail        = document.getElementById("tab-detail");
const tabAudioToggle   = document.getElementById("tab-audio-toggle");
const statWords      = document.getElementById("stat-words");
const statDuration   = document.getElementById("stat-duration");
const statSegments   = document.getElementById("stat-segments");
const statSource     = document.getElementById("stat-source");
const footerInfo     = document.getElementById("footer-info");

// ─────────────────────────────────────────────────────────────────────────────
//  STATE
// ─────────────────────────────────────────────────────────────────────────────
let audioCapture   = null;
let speechMic      = null;
let isRecording    = false;
let timerInterval  = null;
let elapsedSeconds = 0;
let segmentCount   = 0;
let generatedMarkdown = "";
let finalCombinedTranscript = "";
let sessionStart   = null;
let hasMic = false;
let hasTab = false;

// ─────────────────────────────────────────────────────────────────────────────
//  INIT — Load saved settings
// ─────────────────────────────────────────────────────────────────────────────
(async () => {
  const savedKey  = await storageGet("gemini_api_key");
  const savedLang = await storageGet("recognition_lang");
  if (savedKey)  apiKeyInput.value = savedKey;
  if (savedLang) langSelect.value  = savedLang;

  if (!SpeechTranscriber.isSupported()) {
    showAlert("⚠️ Web Speech API not available. Please use Chrome.", "error");
  }

})();

// ─────────────────────────────────────────────────────────────────────────────
//  UI HELPERS
// ─────────────────────────────────────────────────────────────────────────────
function setStatus(state, text) {
  statusBadge.className = `status-badge ${state}`;
  statusText.textContent = text;
}

function showAlert(msg, type = "warning") {
  alertBanner.className = `alert-banner ${type} show`;
  alertTextEl.textContent = msg;
}

function hideAlert() {
  alertBanner.className = "alert-banner";
}

function showLoading(text, sub) {
  loadingText.textContent = text;
  loadingSub.textContent  = sub;
  loadingOverlay.classList.add("show");
}

function hideLoading() {
  loadingOverlay.classList.remove("show");
}

function updateClock(seconds) {
  sessionClock.textContent = formatDuration(seconds);
  sessionClock.classList.toggle("active", isRecording);
}

function updateStats(transcript) {
  const words = transcript.trim() === "" ? 0 :
    transcript.trim().split(/\s+/).filter(w => !["[MIC]","[TAB]"].includes(w)).length;
  statWords.textContent     = words;
  statDuration.textContent  = `${Math.floor(elapsedSeconds / 60)}m`;
  statSegments.textContent  = segmentCount;
  statSource.textContent    = hasMic && hasTab ? "2" : hasMic ? "1" : "—";
}

function updateTranscriptDisplay(full, interim) {
  transcriptEmpty.style.display = "none";

  // Format [MIC] and [TAB] labels with color spans
  const formatted = full
    .replace(/\[MIC\]/g, '<span class="label-mic">[MIC]</span>')
    .replace(/\[TAB\]/g, '<span class="label-tab">[TAB]</span>');

  transcriptEl.innerHTML = formatted +
    (interim ? `<span class="interim-text"> ${interim}…</span>` : "");

  // Auto-scroll
  const area = document.getElementById("transcript-area");
  area.scrollTop = area.scrollHeight;

  updateStats(full);
}

// ─────────────────────────────────────────────────────────────────────────────
//  TAB SWITCHING
// ─────────────────────────────────────────────────────────────────────────────
document.querySelectorAll(".tab-btn").forEach(btn => {
  btn.addEventListener("click", () => {
    const target = btn.dataset.tab;
    document.querySelectorAll(".tab-btn").forEach(b => b.classList.remove("active"));
    document.querySelectorAll(".tab-panel").forEach(p => p.classList.remove("active"));
    btn.classList.add("active");
    document.getElementById(`panel-${target}`).classList.add("active");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
//  API KEY — save on change, toggle visibility
// ─────────────────────────────────────────────────────────────────────────────
apiKeyInput.addEventListener("change", async () => {
  await storageSet("gemini_api_key", apiKeyInput.value.trim());
});

langSelect.addEventListener("change", async () => {
  await storageSet("recognition_lang", langSelect.value);
});

toggleKeyBtn.addEventListener("click", () => {
  apiKeyInput.type = apiKeyInput.type === "password" ? "text" : "password";
});

// ─────────────────────────────────────────────────────────────────────────────
//  START RECORDING
// ─────────────────────────────────────────────────────────────────────────────
btnStart.addEventListener("click", async () => {
  hideAlert();

  // Validate API key early
  const apiKey = apiKeyInput.value.trim();
  if (!apiKey) {
    showAlert("Please enter your Gemini API key in Settings before starting.", "error");
    return;
  }

  // Save key in case user hadn't focused away
  await storageSet("gemini_api_key", apiKey);
  await storageSet("recognition_lang", langSelect.value);

  setStatus("processing", "Initializing…");
  btnStart.disabled = true;

  // ── Reset state ──
  if (speechMic) speechMic.reset();
  transcriptEl.innerHTML = "";
  minutesEl.innerHTML    = "";
  transcriptEmpty.style.display  = "flex";
  minutesEmpty.style.display     = "flex";
  generatedMarkdown = "";
  finalCombinedTranscript = "";
  segmentCount = 0;
  elapsedSeconds = 0;
  hasMic = false;
  hasTab = false;
  updateClock(0);
  updateStats("");

  audioCapture = new AudioCapture();

  // ── Step 1: Mic — request permission and grab label, then release the stream
  // so Web Speech API has exclusive hardware access (holding getUserMedia open
  // simultaneously causes silence on Windows WASAPI).
  let micLabel = "Microphone";
  try {
    const micStream = await audioCapture.captureMic();
    micLabel = micStream.getAudioTracks()[0]?.label || "Microphone";
    // Release immediately — Web Speech API manages its own mic access
    micStream.getTracks().forEach(t => t.stop());
    audioCapture.micStream = null;
    hasMic = true;
    micStatus.textContent = "Active";
    micStatus.className   = "source-pill active";
    micDetail.textContent = micLabel;
  } catch (err) {
    showAlert(err.message, "error");
    setStatus("error", "Error");
    btnStart.disabled = false;
    return;
  }

  // ── Step 2: Tab Audio (optional, via getDisplayMedia dialog) ──
  let tabStream = null;

  if (tabAudioToggle.checked) {
    setStatus("processing", "Waiting for tab selection…");
    showAlert("📌 Chrome's share dialog is opening — select your tab and tick 'Share tab audio'.", "info");
    try {
      tabStream = await audioCapture.captureTabWithDialog();
    } catch (err) {
      if (err.message !== "Tab audio capture was cancelled.") {
        showAlert(`⚠️ ${err.message}`, "warning");
      } else {
        hideAlert();
      }
    }
  }

  if (tabStream) {
    hasTab = true;
    tabStatus.textContent = "Active";
    tabStatus.className   = "source-pill active";
    tabDetail.textContent = tabStream.getAudioTracks()[0]?.label || "Tab Audio";
    audioCapture.startTabRecorder(tabStream);
    hideAlert();
    showAlert("✅ Mic + Tab audio captured. Recording both sources.", "success");
  } else {
    tabStatus.textContent = "Off";
    tabStatus.className   = "source-pill inactive";
    tabDetail.textContent = tabAudioToggle.checked ? "Cancelled — mic only" : "Not enabled";
    if (!tabAudioToggle.checked) hideAlert();
  }

  sessionStart = new Date();

  // ── Step 3: Start Speech Recognition ──
  // Brief pause so the released mic stream's hardware lock clears before Web Speech API claims it
  await new Promise(r => setTimeout(r, 250));

  speechMic = new SpeechTranscriber();
  speechMic.label = "[MIC]";

  speechMic.onTranscriptUpdate = (full, interim) => {
    segmentCount++;
    updateTranscriptDisplay(full, interim);
  };

  speechMic.onNoSpeech = () => {
    // Show a transient hint so the user knows the mic is active but not hearing audio
    setStatus("listening", "Listening… (no audio detected yet)");
    setTimeout(() => { if (isRecording) setStatus("listening", "Listening…"); }, 2000);
  };

  speechMic.onError = (msg) => {
    console.error("[MeetScribe]", msg);
    showAlert(`Recognition error: ${msg}`, "error");
  };

  try {
    speechMic.start(langSelect.value);
  } catch (err) {
    showAlert(err.message, "error");
    setStatus("error", "Error");
    btnStart.disabled = false;
    await audioCapture.stopAll();
    return;
  }

  // ── Step 4: Timer ──
  isRecording = true;
  timerInterval = setInterval(() => {
    elapsedSeconds++;
    updateClock(elapsedSeconds);
    updateStats(speechMic?.getTranscript() || "");
  }, 1000);

  // ── Update UI ──
  setStatus("listening", "Listening…");
  waveIndicator.classList.add("active");
  btnStart.disabled      = true;
  btnStop.disabled       = false;
  btnGenerate.disabled   = true;
  btnDownload.disabled   = true;
  btnTranscript.disabled = true;

  footerInfo.textContent = `Recording started · ${formatTimestamp(sessionStart)}`;
});

// ─────────────────────────────────────────────────────────────────────────────
//  STOP RECORDING
// ─────────────────────────────────────────────────────────────────────────────
btnStop.addEventListener("click", async () => {
  if (!isRecording) return;
  isRecording = false;

  clearInterval(timerInterval);
  waveIndicator.classList.remove("active");
  setStatus("processing", "Stopping…");
  btnStop.disabled = true;

  // Stop speech recognition — get final mic transcript
  const micTranscript = speechMic ? speechMic.stop() : "";

  // Stop audio streams — get tab audio blob if captured
  const tabAudioBlob = await audioCapture.stopAll();

  // Reset source pills
  micStatus.textContent = "Done";
  micStatus.className   = "source-pill inactive";
  tabStatus.textContent = hasTab ? "Done" : "N/A";
  tabStatus.className   = "source-pill inactive";

  // Transcribe tab audio with Gemini if we have it
  let tabTranscript = "";
  if (hasTab && tabAudioBlob && tabAudioBlob.size > 0) {
    setStatus("processing", "Transcribing tab audio…");
    showAlert("🎧 Transcribing tab/meeting audio with Gemini…", "info");
    try {
      const apiKey = apiKeyInput.value.trim();
      const rawTab = await transcribeTabAudio(apiKey, tabAudioBlob);
      if (rawTab) {
        // Label each sentence with [TAB]
        tabTranscript = rawTab
          .split(/(?<=[.?!])\s+/)
          .map(s => `[TAB] ${s.trim()}`)
          .join(" ");
      }
    } catch (err) {
      console.warn("[MeetScribe] Tab transcription error:", err.message);
      showAlert(`⚠️ Tab audio transcription failed: ${err.message}`, "warning");
    }
  }

  // Merge mic + tab transcripts
  const combined = [micTranscript, tabTranscript].filter(Boolean).join(" ");
  const finalTranscript = cleanTranscript(combined);
  finalCombinedTranscript = finalTranscript;

  // Update display with final transcript
  updateTranscriptDisplay(finalTranscript, "");
  updateStats(finalTranscript);

  if (!finalTranscript || finalTranscript.length < 10) {
    setStatus("error", "No Speech Detected");
    showAlert("No speech was detected. Make sure your microphone is working, or enable tab audio sharing for browser/Zoom audio.", "error");
    btnStart.disabled      = false;
    btnGenerate.disabled   = true;
    btnTranscript.disabled = true;
    return;
  }

  setStatus("done", "Ready");
  hideAlert();
  showAlert(`✅ Recording complete. ${finalTranscript.split(" ").length} words captured. Click "Generate Minutes" to create your MoM.`, "success");

  btnStart.disabled      = false;
  btnGenerate.disabled   = false;
  btnDownload.disabled   = true;
  btnTranscript.disabled = false;

  footerInfo.textContent = `Recording stopped · Duration: ${formatDuration(elapsedSeconds)}`;
});

// ─────────────────────────────────────────────────────────────────────────────
//  GENERATE MINUTES
// ─────────────────────────────────────────────────────────────────────────────
btnGenerate.addEventListener("click", async () => {
  const apiKey = apiKeyInput.value.trim();
  if (!apiKey) {
    showAlert("Gemini API key is required. Enter it in Settings.", "error");
    return;
  }

  const transcript = finalCombinedTranscript
    || speechMic?.fullTranscript?.trim()
    || transcriptEl.innerText?.trim()
    || "";

  if (!transcript || transcript.length < 20) {
    showAlert("Transcript is too short. Please record a longer meeting.", "error");
    return;
  }

  hideAlert();
  showLoading("Generating Minutes of Meeting…", "Sending transcript to Gemini 1.5 Flash 8B");
  btnGenerate.disabled = true;
  setStatus("processing", "AI Processing…");

  try {
    const meetingDate = formatTimestamp(sessionStart || new Date());
    const durationMin = Math.ceil(elapsedSeconds / 60) || 1;

    generatedMarkdown = await generateMinutes(apiKey, transcript, meetingDate, durationMin);

    // Switch to minutes tab
    document.querySelector('[data-tab="minutes"]').click();

    minutesEmpty.style.display = "none";
    minutesEl.innerHTML = renderMarkdown(generatedMarkdown);

    hideLoading();
    setStatus("done", "Done ✓");
    hideAlert();
    showAlert("✅ Minutes generated successfully! Click 'Download .md' to save.", "success");

    btnDownload.disabled = false;
    btnGenerate.disabled = false;
    footerInfo.textContent = `MoM generated · ${formatTimestamp(new Date())}`;

  } catch (err) {
    hideLoading();
    setStatus("error", "AI Error");
    showAlert(`Gemini error: ${err.message}`, "error");
    btnGenerate.disabled = false;
    console.error("[MeetScribe] Gemini error:", err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
//  DOWNLOAD
// ─────────────────────────────────────────────────────────────────────────────
btnDownload.addEventListener("click", () => {
  if (!generatedMarkdown) {
    showAlert("No minutes to download. Generate minutes first.", "warning");
    return;
  }

  downloadFile(generatedMarkdown, "minute_of_meeting.md", "text/markdown");
  showAlert("✅ Downloading minute_of_meeting.md …", "success");
});

btnTranscript.addEventListener("click", () => {
  const transcript = finalCombinedTranscript
    || speechMic?.fullTranscript?.trim()
    || transcriptEl.innerText?.trim()
    || "";

  if (!transcript) {
    showAlert("No transcript to download. Record a meeting first.", "warning");
    return;
  }

  const timestamp = formatTimestamp(sessionStart || new Date());
  const content = `MeetScribe — Transcript\n${timestamp}\n${"=".repeat(40)}\n\n${transcript}`;
  downloadFile(content, "transcript.txt", "text/plain");
  showAlert("✅ Downloading transcript.txt …", "success");
});

// ─────────────────────────────────────────────────────────────────────────────
//  SAFETY — warn before closing tab during recording
// ─────────────────────────────────────────────────────────────────────────────
window.addEventListener("beforeunload", (e) => {
  if (isRecording) {
    e.preventDefault();
    e.returnValue = "Recording is in progress. Are you sure you want to leave?";
  }
});
