// gemini.js — Gemini AI Integration
// Sends meeting transcript to Gemini 1.5 Flash and returns
// a professionally structured Markdown Minutes of Meeting.

const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

/**
 * Transcribe a tab audio blob using Gemini's multimodal audio input.
 * @param {string} apiKey
 * @param {Blob} audioBlob - WebM audio blob from MediaRecorder
 * @returns {Promise<string>} - Plain text transcript
 */
export async function transcribeTabAudio(apiKey, audioBlob) {
  // Convert blob to base64 via FileReader (handles large files cleanly)
  const base64 = await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result.split(",")[1]);
    reader.onerror = reject;
    reader.readAsDataURL(audioBlob);
  });

  const requestBody = {
    contents: [{
      parts: [
        { text: "Transcribe the following audio accurately. Output only the spoken words as plain text. Do not add punctuation styles, formatting, labels, or commentary — just the raw transcribed speech." },
        { inline_data: { mime_type: audioBlob.type || "audio/webm", data: base64 } }
      ]
    }],
    generationConfig: { temperature: 0.1, maxOutputTokens: 4096 },
  };

  const response = await fetch(`${GEMINI_API_BASE}?key=${apiKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err?.error?.message || `HTTP ${response.status}`);
  }

  const data = await response.json();
  return data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
}

/**
 * Build the professional MoM prompt.
 * @param {string} transcript - Raw meeting transcript
 * @param {string} meetingDate - Formatted date string
 * @param {number} durationMinutes - Meeting duration in minutes
 */
function buildMoMPrompt(transcript, meetingDate, durationMinutes) {
  return `You are a professional meeting secretary. Your task is to convert a raw meeting transcript into a clean, structured, and professional "Minutes of Meeting" document in Markdown format.

MEETING METADATA:
- Date: ${meetingDate}
- Duration: approximately ${durationMinutes} minutes
- Transcript Source: Mixed (microphone + tab audio, labeled [MIC] for participant and [TAB] for meeting audio)

RAW TRANSCRIPT:
---
${transcript}
---

INSTRUCTIONS:
1. Carefully analyze the full transcript above.
2. Generate a complete "Minutes of Meeting" document in Markdown.
3. Use the structure defined below EXACTLY.
4. Be concise but complete — capture all important information.
5. Fix minor speech-to-text errors and clean up filler words (um, uh, like).
6. If a section has no relevant content from the transcript, write "Not discussed."
7. For Action Items, always include: What, Who (if mentioned), and Deadline (if mentioned).
8. Output ONLY the Markdown document — no preamble, no explanation, no code fences.

REQUIRED OUTPUT STRUCTURE:

# Minutes of Meeting

**Date:** ${meetingDate}
**Duration:** ${durationMinutes} minutes
**Recorded by:** MeetScribe AI

---

## 1. Attendees
> List any names, roles, or references to participants mentioned in the transcript.

## 2. Agenda
> List topics that were planned or mentioned at the start of the meeting.

## 3. Key Discussion Points
> For each major topic discussed, create a sub-section:
### 3.1 [Topic Name]
- Key points discussed
- Arguments or perspectives raised
- Any data, numbers, or references mentioned

## 4. Decisions Made
> Bullet list of all decisions, agreements, or conclusions reached.
- [ ] Decision 1
- [ ] Decision 2

## 5. Action Items
> Table format:
| # | Action | Owner | Deadline | Status |
|---|--------|-------|----------|--------|
| 1 | ...    | ...   | ...      | Open   |

## 6. Next Steps
> What happens after this meeting? Next meeting date if mentioned.

## 7. Additional Notes
> Any other relevant context, concerns, or off-topic items worth recording.

---
*Generated by MeetScribe AI · Powered by Gemini 1.5 Flash 8B*`;
}

/**
 * Call Gemini API to generate Minutes of Meeting.
 * @param {string} apiKey - User's Gemini API key
 * @param {string} transcript - Raw meeting transcript
 * @param {string} meetingDate - Human-readable date
 * @param {number} durationMinutes - Duration in minutes
 * @returns {Promise<string>} - Markdown MoM content
 */
export async function generateMinutes(apiKey, transcript, meetingDate, durationMinutes) {
  if (!apiKey || apiKey.trim() === "") {
    throw new Error("Gemini API key is missing. Please enter your API key in settings.");
  }

  if (!transcript || transcript.trim().length < 20) {
    throw new Error("Transcript is too short or empty. Please record a longer meeting segment.");
  }

  const prompt = buildMoMPrompt(transcript.trim(), meetingDate, durationMinutes);

  const requestBody = {
    contents: [
      {
        parts: [
          { text: prompt }
        ]
      }
    ],
    generationConfig: {
      temperature: 0.3,        // Low temp for factual, consistent output
      topK: 40,
      topP: 0.9,
      maxOutputTokens: 4096,
      candidateCount: 1,
    },
    safetySettings: [
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" },
    ],
  };

  const url = `${GEMINI_API_BASE}?key=${apiKey}`;

  let response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });
  } catch (networkErr) {
    throw new Error(`Network error while contacting Gemini: ${networkErr.message}`);
  }

  if (!response.ok) {
    let errorDetail = "";
    try {
      const errJson = await response.json();
      errorDetail = errJson?.error?.message || JSON.stringify(errJson);
    } catch (_) {
      errorDetail = await response.text();
    }

    if (response.status === 400) throw new Error(`Gemini: Bad request — ${errorDetail}`);
    if (response.status === 403) throw new Error("Gemini: Invalid API key or access denied. Check your API key.");
    if (response.status === 429) throw new Error("Gemini: Rate limit exceeded. Wait a moment and try again.");
    if (response.status === 500) throw new Error("Gemini: Server error. Try again in a few moments.");
    throw new Error(`Gemini API error (${response.status}): ${errorDetail}`);
  }

  const data = await response.json();

  // Extract generated text
  const candidate = data?.candidates?.[0];
  if (!candidate) {
    throw new Error("Gemini returned no candidates. The transcript may have triggered a content filter.");
  }

  // Check for safety blocks
  if (candidate.finishReason === "SAFETY") {
    throw new Error("Gemini flagged the content for safety. Try shortening the transcript.");
  }

  const text = candidate?.content?.parts?.[0]?.text;
  if (!text || text.trim() === "") {
    throw new Error("Gemini returned an empty response. Please try again.");
  }

  return text.trim();
}
